// Generated by CoffeeScript 1.8.0
(function() {
  var Twit, cheerio, readJSON, request;

  cheerio = require('cheerio');

  request = require('request');

  Twit = require('twit');

  readJSON = require('read-json');

  readJSON('./credentials.json', function(err, credentials) {
    var T, form, message, url;
    T = new Twit({
      consumer_key: credentials.consumer_key,
      consumer_secret: credentials.consumer_secret,
      access_token: credentials.access_token,
      access_token_secret: credentials.access_token_secret
    });
    message = "yo @milushov, ur tickets found!\n\n(message from bot -- http://goo.gl/z6bu1M)";
    url = 'http://94.19.37.202:3069/cgi-bin/tcgi1.exe';
    form = {
      USER: null,
      COMMAND: 3000,
      PASSWORD: 46,
      NAMESHOWFILE: null
    };
    return request.post({
      url: url,
      form: form
    }, function(error, response, body) {
      var $, found;
      found = false;
      $ = cheerio.load(body);
      return $('td').each(function(i, el) {
        var id, td, tickets_count;
        td = $(el);
        if (td.text() === '������������') {
          id = td.prev().prev().text();
          if (id === '15' || id === '16') {
            if (found) {
              return;
            }
            tickets_count = td.next().next().text();
            console.info("tickets count on " + (new Date) + " --- ", tickets_count);
            if (parseInt(tickets_count) > 0) {
              found = true;
              console.info('yay!');
              return T.post('statuses/update', {
                status: message
              }, function() {});
            }
          }
        }
      });
    });
  });

}).call(this);
